CREATE DATABASE LAN_HOUSE

USE LAN_HOUSE

CREATE TABLE TIPOS_DEFEITO (
	ID INT NOT NULL Primary KEY IDENTITY(1,1),
	NOME VARCHAR(100) NOT NULL 
)

CREATE TABLE EQUIPAMENTOS (
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	NOME VARCHAR(100) NOT NULL
)

CREATE TABLE REGISTROS_DEFEITOS (
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	DATA_DEFEITO DATETIME NOT NULL,
	ID_EQUIPAMENTO INT NOT NULL FOREIGN KEY REFERENCES EQUIPAMENTOS(ID),
	ID_DEFEITO INT NOT NULL FOREIGN KEY REFERENCES TIPOS_DEFEITO(ID),
	OBSERVACAO TEXT
)


CREATE TABLE USUARIOS(
	ID INT NOT NULL Primary Key IDENTITY(1,1),
	EMAIL VARCHAR(100) NOT NULL,
	SENHA VARCHAR(50) NOT NULL,
)